### ISSUE TITLE
Make nested child pages in Certifications

### ISSUE THREAD

**Issue by rstender** [hypenotic/pfennings#105]
Hi @ajay786singh,
The client would like the Certifications child pages to show on the Certifications page, much like they do on the services page.

So...
Certifications: http://pfenningsfarms.ca/certifications/

Should pull in child pages like: 
Services: http://pfenningsfarms.ca/our-services/

Thanks,

-rs-

**Comment by ajay786singh** [comment]
It's done. If you want to make any other page to same as http://pfenningsfarms.ca/our-services/ with child pages. You just need to select page template odd/even from admin.

**Comment by rstender** [comment]
I tried it and it didn't work. What did I Di wrong?

**Comment by lmann** [comment]
Looks like this has been fixed. Closing this issue
