### ISSUE TITLE
Site name disappears on mobile here: http://pfenningsfarms.ca/order-now/

### ISSUE THREAD

**Issue by barrymartin** [hypenotic/pfennings#151]

**Comment by ajay786singh** [comment]
I didn't get this issue send me a screenshot Please.

**Comment by lmann** [comment]
@barrymartin I can see site title on mobile. Please clarify or send screenshot

**Comment by lmann** [comment]
I figured this out. This a problem for the pfennings near you

**Comment by lmann** [comment]
closing this and created a new issue for this with screenshot. See issue #156
