### ISSUE TITLE
Main title ("Pfenning's Near you!") loads in a weird place on mobile and desktop: http://pfenningsfarms.ca/pfennings-near-you-2/

### ISSUE THREAD

**Issue by barrymartin** [hypenotic/pfennings#153]
![img_8982](https://cloud.githubusercontent.com/assets/1844978/6998864/f06eaa1c-dbbd-11e4-9bb3-0051a0982ea9.PNG)
![screen shot 2015-04-05 at 5 59 08 pm](https://cloud.githubusercontent.com/assets/1844978/6998867/ff010dc2-dbbd-11e4-9078-c0342920ede8.png)

**Comment by lmann** [comment]
Closing this. See issue #156
