### ISSUE TITLE
Title is offcenter

### ISSUE THREAD

**Issue by lmann** [hypenotic/pfennings#174]
The title "Pfennings Near You" is not centered

![screen shot 2015-04-07 at 5 16 07 pm](https://cloud.githubusercontent.com/assets/1795752/7033677/d5da7f2c-dd49-11e4-938a-da871875bb4d.png)

**Comment by ajay786singh** [comment]
Please check, title is on center.

**Comment by lmann** [comment]
I just did. It isnt on center on hypelabs
![screen shot 2015-04-07 at 10 58 19 pm](https://cloud.githubusercontent.com/assets/1795752/7038038/a73b34ce-dd79-11e4-92a1-5131881bfa78.png)

**Comment by lmann** [comment]
Hi Ajay

This is still not centered vertically. Can you not use the other display flex table as I've done before in all the other templates??

**Comment by lmann** [comment]
![screen shot 2015-04-08 at 8 16 09 am](https://cloud.githubusercontent.com/assets/1795752/7045022/8c18a1e2-ddc7-11e4-8c94-5cdd6c8762ae.png)

**Comment by lmann** [comment]
![screen shot 2015-04-08 at 8 17 03 am](https://cloud.githubusercontent.com/assets/1795752/7045032/a89987be-ddc7-11e4-8e8d-d549d0433fe5.png)
