### ISSUE TITLE
This 

### ISSUE THREAD

**Issue by rstender** [hypenotic/pfennings#230]
Hey @ajay786singh,
For some reason, for this particular blog post, the featured image doesn't appear when you share it on Facebook.

http://pfenningsfarms.ca/fiddleheads/

Could you see if you can figure out why not?

-rs-

**Comment by ajay786singh** [comment]
Hey @rstender , Actually facebook takes times to fetch fresh data from sites. It takes about 24 Hours to re-scraps pages. That's why, there is no featured image for new post.

**Comment by rstender** [comment]
@ajay786singh - That's very useful info. Thanks @ajay786singh!
