### ISSUE TITLE
Tagline is unreadable across the site

### ISSUE THREAD

**Issue by barrymartin** [hypenotic/pfennings#47]
Need to make a version that just writes it out horizontally
![screen shot 2015-02-09 at 11 52 39 am](https://cloud.githubusercontent.com/assets/1844978/6110852/9bfa559e-b052-11e4-88f1-b63700e1b653.png)

**Comment by lmann** [comment]
@barrymartin we've made the logo bigger. It's more readable but if you still find it too small we can reopen this issue.
