### ISSUE TITLE
Certification links from Home page to a new page called Certifications

### ISSUE THREAD

**Issue by barrymartin** [hypenotic/pfennings#53]
The Certifications page will have a blurb about certifications in general.
Organic.
Canada GAP (Good Agricultural Practices)

http://www.canadagap.ca/

**Comment by rstender** [comment]
Should I be asking for a blurb, or are there raw materials for writing this?

**Comment by lmann** [comment]
@rstender can this be closed?

**Comment by rstender** [comment]
I believe so.
