### ISSUE TITLE
Grain Mills: 

### ISSUE THREAD

**Issue by barrymartin** [hypenotic/pfennings#54]
Reconnect Price List on Grain Mills page

**Comment by lmann** [comment]
This will need to be seperated out into individual task issues

**Comment by barrymartin** [comment]
K. After my meeting.

**Comment by lmann** [comment]
These need to be broken into tasks. Not sure if any of them should really be as a gh issue.

**Comment by lmann** [comment]
Closing this issue as it looks like it is done.
