### ISSUE TITLE
Hamburger and Menu

### ISSUE THREAD

**Issue by lmann** [hypenotic/pfennings#58]
The hamburger icon looks way too big. Can you make it the same size as before?

![image](https://cloud.githubusercontent.com/assets/1795752/6129635/db2d607e-b10d-11e4-946e-9c85fe673b71.png)

**Comment by lmann** [comment]
@ajay786singh actually, I see you've also changed the hamburger menu animation. Can you revert to what it was before. Just add "Menu" in front of it.

**Comment by ajay786singh** [comment]
Please check this issue should be close now.
