### ISSUE TITLE
Design: Pfennings near you

### ISSUE THREAD

**Issue by lmann** [hypenotic/pfennings#59]
Can you make the pfennings near you more like this page with the search form fields in the sidebar as per http://pfenningsfarms.ca/pfennings-near-you/

![image](https://cloud.githubusercontent.com/assets/1795752/6129872/52892936-b10f-11e4-8f44-ef47e79e3b2b.png)

**Comment by lmann** [comment]
@ajay786singh any movement on this??

**Comment by ajay786singh** [comment]
Please check here: http://pfenningsfarms.ca/pfennings-near-you-2/

**Comment by lmann** [comment]
@ajay786singh placement of items in rows is off

![screen shot 2015-02-17 at 11 04 18 am](https://cloud.githubusercontent.com/assets/1795752/6231616/d3f4a8e4-b694-11e4-88eb-c7602bda735f.png)

**Comment by lmann** [comment]
Actually, forget that, just noticed it's correct on hypelabs.
