### ISSUE TITLE
Our story page header is smaller than other page headers

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/pfennings#65]

**Comment by lmann** [comment]
@jenphelan what should be done for this?

**Comment by jenphelan** [comment]
![screen shot 2015-02-17 at 3 42 19 pm](https://cloud.githubusercontent.com/assets/10924897/6236797/9c342160-b6bb-11e4-9cae-d74fc3627e3a.png)
Please make the smaller page headers the same size as the others. (48.8 pt)
