### ISSUE TITLE
Pfenning's Near You: Sidebar

### ISSUE THREAD

**Issue by SamChun** [hypenotic/pfennings#79]
As per the reference image:

Header text: All caps
Button colour: Pfenning's orange
Font-size: 16px
Decrease width.
Increase space between sidebar and locations (should be full column width and gutters).

**Comment by lmann** [comment]
![d597dd94-b917-11e4-83a5-0b5311e742ed](https://cloud.githubusercontent.com/assets/1795752/6567933/09f832aa-c6a6-11e4-94bd-47a1f2363d88.jpg)
