### ISSUE TITLE
Pfenning's Near You: Home Delivery

### ISSUE THREAD

**Issue by SamChun** [hypenotic/pfennings#80]
As per the reference image:

Start addresses on the same line.
Make addresses: 13px
Store name: 16px

**Comment by lmann** [comment]
![d597dd94-b917-11e4-83a5-0b5311e742ed](https://cloud.githubusercontent.com/assets/1795752/6567940/20c5a2b0-c6a6-11e4-9419-71d55f4e2fc0.jpg)
