### ISSUE TITLE
Make all mobile contact buttons the same green

### ISSUE THREAD

**Issue by rstender** [hypenotic/pfennings#81]
On this page: http://pfenningsfarms.ca/team/staff/ , please change the blue buttons to match the green ones.

I think they're supposed to be Pfennings green #10824a.

**Comment by rstender** [comment]
Update: All buttons should be green. The Pfennings green is #10824a.

I'm passing this to @SamChun, since I understand he's already working on it.

**Comment by lmann** [comment]
Im going to reference issue #87 for button colours as per mockup. All buttons orange with green rollover. Closing this issue.
