### ISSUE TITLE
Page banners

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/pfennings#83]
Issue a) 
On a 13'' screen, the text in the banner starts too high and crashes into the logo. Please set up a safe zone under the logo/ tagline where this doesn't happen.

Issue b)
Is it possible to make the underlines under links in the banner text (see home page) closer to the words? see mockup.

Issue c)
Some banner text (connect page, grain mills) starts in the center of the page, unlike the other pages. Please align all banner text to the same grid.

**Comment by jenphelan** [comment]
![screen shot 2015-02-25 at 12 24 10 pm](https://cloud.githubusercontent.com/assets/10924897/6378565/3f817a22-bcfa-11e4-96d5-452da9e1e7aa.png)

**Comment by jenphelan** [comment]
![screen shot 2015-02-25 at 12 27 41 pm](https://cloud.githubusercontent.com/assets/10924897/6378576/4e1ec24c-bcfa-11e4-8259-c717b43b16b7.png)

**Comment by lmann** [comment]
Hi Jen
Re: Issue b)
Barry said that he likes the underlines for links further away.

Issue c)
Don't understand comment. Please clarify.

**Comment by lmann** [comment]
done
