### ISSUE TITLE
Services

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/pfennings#86]
Issue a)

See mockup. photos should go to halfway point on page. If there is not photo, this space should remain empty.

Issue b) 
We need to take out all the details from the first Service (Growing) Instead there should be a button that links to the order page. Sam will mockup and share.

![screen shot 2015-02-25 at 12 25 29 pm](https://cloud.githubusercontent.com/assets/10924897/6378253/0d3220d2-bcf8-11e4-9965-289973d88f9c.png)

**Comment by SamChun** [comment]
![pfennings_services](https://cloud.githubusercontent.com/assets/8697960/6381505/976fcb7a-bd0f-11e4-89ac-5ae491e51335.jpg)
