### ISSUE TITLE
Connect

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/pfennings#87]
issue a)

The side bar should appear on the left

issue b)

The side bar is too wide (see mockup)

issue c)

By decreasing the side bar width, that should allow 3 staff to appear on each line (see mockup)

issue d)

Not all buttons are consistent on the site. Let's make them all orange, with rollover green. (Except in footer, it can be white, rollover green). See mockup.

![screen shot 2015-02-25 at 12 27 58 pm](https://cloud.githubusercontent.com/assets/10924897/6378294/6ec76adc-bcf8-11e4-896e-c98df4a7e539.png)

**Comment by SamChun** [comment]
![pfennings_contact](https://cloud.githubusercontent.com/assets/8697960/6381490/8baf8172-bd0f-11e4-8a58-9d8e36eeee88.jpg)

**Comment by lmann** [comment]
The Pfennings green is #10824a
