### ISSUE TITLE
Grain mill page

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/pfennings#89]
Issue a)

Very different from mockup. Sam will repost his psd of what should be happening.

**Comment by jenphelan** [comment]
![screen shot 2015-02-25 at 12 27 17 pm](https://cloud.githubusercontent.com/assets/10924897/6378600/71dac2c6-bcfa-11e4-8a47-53ba64284997.png)

**Comment by SamChun** [comment]
![pfennings_grainmill](https://cloud.githubusercontent.com/assets/8697960/6381467/71690ff4-bd0f-11e4-8aa8-f4c91da414ff.jpg)

**Comment by lmann** [comment]
@SamChun @jenphelan lets talk about this before implementation
