### ISSUE TITLE
Our story page

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/pfennings#90]
Should follow same mockup as services page. We need image options for each heading, going to the middle of the page. 

![screen shot 2015-02-25 at 12 25 07 pm](https://cloud.githubusercontent.com/assets/10924897/6378399/114f1386-bcf9-11e4-982e-e3cf1ecd93bc.png)

**Comment by lmann** [comment]
@SamChun lets talk about this before you fix.

**Comment by lmann** [comment]
This is complete
