### ISSUE TITLE
Blog page

### ISSUE THREAD

**Issue by jenphelan** [hypenotic/pfennings#91]
Issue a) 

Content pulled in from blog posts do not have picture option. It looks awkward, because content pulled in from other feeds on the page do have pictures. Can you add an option to upload a picture to the post that will show on this archive page?

Issue b)

Sam will mockup this page, but we're thinking we don't need the side bar which is empty. Instead, posts can go at least 4 across. Maybe 5. 

![screen shot 2015-02-25 at 12 27 17 pm](https://cloud.githubusercontent.com/assets/10924897/6378460/8c384e82-bcf9-11e4-8083-cc7915760fc0.png)

**Comment by SamChun** [comment]
![archive](https://cloud.githubusercontent.com/assets/8697960/6381561/01693f3e-bd10-11e4-90a1-801caae9cf12.jpg)
![blog post](https://cloud.githubusercontent.com/assets/8697960/6381560/0168c0f4-bd10-11e4-8e96-238b5b8b2250.jpg)

**Comment by lmann** [comment]
@jenphelan Barry mentioned that the blog listing is also the social aggregator see issue #62 and #63. We should talk about this before implementation.
