### ISSUE TITLE
Draft blog posts showing on production

### ISSUE THREAD

**Issue by rstender** [hypenotic/pfennings#98]
Hey @ajay786singh, @lmann 
This one's curious...

The client has written a draft blog post called, The Old Oak Door. For some reason, the link is showing under Latest News here: http://pfenningsfarms.ca/

Even stranger, when you click the link, it redirects to the blog post called, "Pfenning's Fluffy Friends."

Can you have a look, please?

-rs-

**Comment by rstender** [comment]
@lmann - I'm leaving this open until you pull it to production.

-rs-

**Comment by ajay786singh** [comment]
this need a server configuration setting to change. 
Hey Lionelm We are getting this warning:
Warning: file_get_contents() [function.file-get-contents]: http:// wrapper is disabled in the server configuration by allow_url_fopen=0 in
 Please check here:
http://pfenningsfarms.ca/blog/

**Comment by lmann** [comment]
This is now working and pulled to production
